### ISSUE TITLE
Null values in prepared statements inside batch cause NoSuchElementException

### ISSUE THREAD

**Issue by mishamo** [scassandra/scassandra-server#137]
E.g. a null Long will throw the following:
`java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
	at akka.util.ByteIterator$ByteArrayIterator.next(ByteIterator.scala:40)
	at akka.util.ByteIterator.getLong(ByteIterator.scala:505)
	at org.scassandra.server.cqlmessages.types.CqlLongType.readValue(CqlLongType.scala:25)
	at org.scassandra.server.actors.BatchHandler.readValue(BatchHandler.scala:104)
	at org.scassandra.server.actors.BatchHandler$$anonfun$receive$1$$anonfun$5$$anonfun$7.apply(BatchHandler.scala:90)
	at org.scassandra.server.actors.BatchHandler$$anonfun$receive$1$$anonfun$5$$anonfun$7.apply(BatchHandler.scala:90)
	at scala.collection.immutable.List.map(List.scala:273)
	at org.scassandra.server.actors.BatchHandler$$anonfun$receive$1$$anonfun$5.apply(BatchHandler.scala:90)
	at org.scassandra.server.actors.BatchHandler$$anonfun$receive$1$$anonfun$5.apply(BatchHandler.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.scassandra.server.actors.BatchHandler$$anonfun$receive$1.applyOrElse(BatchHandler.scala:82)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.scassandra.server.actors.BatchHandler.aroundReceive(BatchHandler.scala:36)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by chbatey** [comment]
this is fixed now right? @mishamo

**Comment by mishamo** [comment]
Yes
