### ISSUE TITLE
scassandra 0.9.0 does not work with JDK6

### ISSUE THREAD

**Issue by tolbertam** [scassandra/scassandra-server#93]
Mistake on my part.  The java-client project properly targets 1.6, but the scassandra-server project does not:

> java.lang.UnsupportedClassVersionError: org/scassandra/server/ServerStubRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.scassandra.ScassandraRunner.<init>(ScassandraRunner.java:46)
	at org.scassandra.ScassandraFactory.createServer(ScassandraFactory.java:39)
	at com.datastax.driver.core.SCassandraCluster.<init>(SCassandraCluster.java:59)
	at com.datastax.driver.core.SpeculativeExecutionTest.beforeClass(SpeculativeExecutionTest.java:44)

Adding the following to the build.gradle for server module should do the trick.  I'll work to fix this.
 
```code:groovy
compileJava {
    sourceCompatibility = "1.6"
    targetCompatibility = "1.6"
}
```

**Comment by tolbertam** [comment]
Also needed to add this to the `compileScala` target as well.  Create #94 for this, sorry about that!

**Comment by chbatey** [comment]
Want to test out 0.9.1-SNAPSHOT before I release again? I have uploaded it to: https://oss.sonatype.org/content/groups/public

**Comment by tolbertam** [comment]
@chbatey giving it a try, thanks!

**Comment by tolbertam** [comment]
@chbatey excellent, looks like that worked :+1:

**Comment by chbatey** [comment]
Releasing :)

**Comment by chbatey** [comment]
Think i also found the reason for the odd travis failures, we responded to prepared statement executions before recording activity, switched it around.

**Comment by chbatey** [comment]
0.9.1 syncing with maven central now, usually takes about 30 mins and is available for download before the website shows it

**Comment by tolbertam** [comment]
awesome, thanks for the quick turnaround :)
